main: de.nicouschulas.betterpaintballsystem.BetterPaintballSystem
version: '${project.version}'
name: Paintball
api-version: '26.1.2'
author: Nicouschulas
softdepend: [Multiverse-Core, Vault, PlaceholderAPI, DecentHolograms]

commands:
  paintball:
    description: Main command of BetterPaintballSystem
    aliases: pb

permissions:
  betterpaintballsystem.update:
    description: Allows a player to receive in-game update notifications.
    default: op
  paintball.admin:
    description: Parent permission for all administrative commands and usage.
    default: op