main: pb.ajneb97.PaintballBattle
version: '${project.version}'
name: Paintball
api-version: '26.1.2'
author: Nicouschulas
softdepend: [Multiverse-Core, Vault, PlaceholderAPI, DecentHolograms]

commands:
  paintball:
    description: Main command of PaintballBattle
    aliases: pb